### ISSUE TITLE
Feature - Develop `reindexTokens` function

### ISSUE THREAD

**Issue by BritikovKI** [PrimeDAO/balancer-v2-monorepo#2]
## User Story
**As**  Indexed Finance I offer users an easy way to invest in a basket of tokens that match certain criteria and when tokens tdo not match the criteria anymore (or suddenly match these criteria), **I want** to be able to remove (add) them, **so that** the pool continues to provide the possibility to invest in tokens that fulfill the criteria.

## Status Quo
- The current IndexPool that is basically a copy of WeightedPool doesn't have a functionality to add/remove tokens
- with `reweighTokens` we introduce a method to rebalance tokens #3 

## Acceptance Criteria
- [ ] when a new token is added its weight is initially set to 1% and the initialization parameters are stored  #10
- [ ] it has been ensured that weight changes are possible while other weight changes are in progress #30
- [ ] util to calculate the weight premium for uninitialized tokens #11
- [ ] weight premium mechanism is embedded for uninitialized token swaps #29 
- [ ] token initialization - #19 
- [x] a design to remove tokens has been developed - #9
- [ ] if tokens are to be removed their weight is to be set to 0.5% - #21 
- [ ] if a token with weight .5% is traded the residual amount is sent to handler contract #28
- [ ] the minimum balance for tokens can be adjusted retrospectively - #12
- [ ] it is fully tested

**Comment by fabianschu** [comment]
this summary is not maintained anymore
