### ISSUE TITLE
Feature - Develop `reweighTokens` function

### ISSUE THREAD

**Issue by BritikovKI** [PrimeDAO/balancer-v2-monorepo#3]
## User Story
**As Index Finance I want a pool to be able to reweigh tokens in the contract so that the pool is composed in a way that reflects my view on the market."

## Status Quo
It is impossible to change the weights of the `weightedPool` contract. They are being set only on the contract creation.

## Acceptance Criteria:
- [x] the function reverts under undesired conditions - #8 
- [x] the function can only be called by the controller - #16
- [x] state: reweighTokens calls `updateWeightsGradually` with a dynamically calculated the desired endTime - #6 
- [x] hooks: the exchange rates for swaps that take place while the pool is being rebalanced are based on the current token weights - #18 
- [ ] it is fully tested

**Comment by fabianschu** [comment]
summary no longer maintained
